### ISSUE TITLE
error build

### ISSUE THREAD

**Issue by fukemy** [georgealexiou/PokemonApp#3]
Unable to resolve "../../Components/Screen/Screen" from "src/Features/GenerationsScreen/GenerationsScreen.tsx"

<img width="352" alt="Screen Shot 2023-02-28 at 10 19 46" src="https://user-images.githubusercontent.com/8202437/221744982-4e123351-2e34-42e6-8678-c01c87532b2f.png">

**Comment by georgealexiou** [comment]
Fixed in pr https://github.com/georgealexiou/PokemonApp/pull/4
